base_url = "https://frogworks404.dev"
title = "frogworks404"
description = "ソフトウェア・ハードウェア・アイデアの記録"
default_language = "ja"
compile_sass = true
build_search_index = false

[[taxonomies]]
name = "tags"

[extra]
start_date = "2024.01"
github = ""
x = "https://x.com/frogworks404"
booth = ""
analytics_provider = "none"
analytics_google_id = "G-GXV2EYXZYE"
analytics_plausible_domain = "flog404.work"
