// Generated by Project Mixer. Safe to delete; hook:setup recreates it.
const HOOK_URL = process.env.PM_HOOK_URL;
const PTY_ID = Number(process.env.PROJECT_MIXER_PTY_ID);

function payload(extra) {
  return {
    agent_source: 'opencode',
    ...(Number.isInteger(PTY_ID) && PTY_ID > 0 ? { pty_id: PTY_ID } : {}),
    cwd: process.cwd(),
    ...extra,
  };
}

function send(extra) {
  if (!HOOK_URL) return;
  // payload() attaches agent_source, pty_id and cwd — without them PM
  // cannot route the event to the originating tab.
  fetch(HOOK_URL, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(payload(extra)),
  }).catch(() => {});
}

export const ProjectMixerPlugin = async () => ({
  event: async ({ event }) => {
    try {
      const type = event && event.type;
      const props = (event && event.properties) || {};
      if (type === 'session.status' && props.status && props.status.type === 'idle') {
        send({ type: 'stop', session_id: props.sessionID });
      } else if (type === 'session.error') {
        send({ type: 'stopfailure', session_id: props.sessionID, message: describeError(props.error) });
      } else if (type === 'permission.asked') {
        send({
          type: 'permissionrequest',
          session_id: props.sessionID,
          tool_name: props.permission || undefined,
          message: permissionDetail(props),
        });
      } else if (type === 'question.asked') {
        send({ type: 'notification', session_id: props.sessionID, title: 'OpenCode is asking a question' });
      }
    } catch {
      // Never break the host session because of a notification failure.
    }
  },
});

function describeError(error) {
  if (!error) return undefined;
  if (typeof error === 'string') return error;
  return error.message || error.name || undefined;
}

function permissionDetail(props) {
  const metadata = props.metadata;
  const detail = metadata && typeof metadata === 'object'
    ? (metadata.message || metadata.title || metadata.description)
    : undefined;
  if (typeof detail !== 'string' || !detail.trim()) {
    return Array.isArray(props.patterns) && props.patterns.length
      ? props.patterns.join(', ')
      : undefined;
  }
  return detail;
}

export default ProjectMixerPlugin;
